import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import React from "react";
import { GlobalProvider } from "./global-provider";
import NavigationBar from "@/components/navigation-bar/navigation-bar";

const dm_sans = DM_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <GlobalProvider>
          <div className="relative flex h-full w-full flex-col items-center justify-center">
            <NavigationBar />
            <div className="h-full w-full flex-1">{children}</div>
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
