import React from "react";
import { Header } from "./_components/header";
import { DividendList } from "./_components/dividend-list";
import { Dividend } from "../_components/dividend-row";

const dummyDividendList: Dividend[] = [
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
];

const YearlyDividendPage = React.memo(() => {
  return (
    <div className="flex size-full flex-col items-center justify-start gap-5">
      <Header />
      <DividendList dividendList={dummyDividendList} />
    </div>
  );
});

export default YearlyDividendPage;
