import React from "react";
import { Header } from "./_components/header";
import { DividendList } from "./_components/dividend-list";
import { Dividend } from "../_components/dividend-row";
import { useYearlyDividendMutation } from "@/state/queries/use-yearly-dividend-mutation";
import { YearlyDividendResponse } from "@/api/generated/endpoint.schemas";

const dummyDividendList: Dividend[] = [
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
  {
    companyName: "companyName",
    exchange: "exchange",
    industry: "industry",
    sectorName: "sectorName",
    stockId: "stockId",
    logoUrl: "/next.svg",
    price: 12,
    volume: 18,
    ticker: "AAPL",
  },
];

const YearlyDividendPage = React.memo(() => {
  const { mutate: mutateYearlyDividend, data: yearlyDividendData } = useYearlyDividendMutation();

  React.useEffect(() => {
    mutateYearlyDividend();
  }, [mutateYearlyDividend]);

  const yearlyDividends: YearlyDividendResponse = React.useMemo(() => {
    return {
      totalDividend: yearlyDividendData?.totalDividend ?? 0,
      dividends:
        yearlyDividendData?.dividends.sort((a, b) => {
          return b.totalDividend - a.totalDividend;
        }) ?? [],
    };
  }, [yearlyDividendData]);

  return (
    <div className="flex size-full flex-col items-center justify-start gap-5">
      <Header />
      <DividendList dividendList={dummyDividendList} />
    </div>
  );
});

export default YearlyDividendPage;
